### ISSUE TITLE
The ResizeObserver shim should not add to `global`

### ISSUE THREAD

**Issue by dasa** [dojo/framework#237]
**Bug ** 

Package Version: 5.0

**Code**

https://github.com/dojo/framework/blob/master/src/shim/ResizeObserver.ts#L34-L38

**Expected behavior:**

It returns the ponyfill: https://github.com/que-etc/resize-observer-polyfill#usage-example

**Actual behavior:**

It sets the ponyfill on `global` and then returns that. This also doesn't work if using an AMD loader that uses the non-ES6 module since `default` is then `undefined`.

**Comment by matt-gadd** [comment]
The expected behaviour is to be on the global for shim and will be going forward as there are not ponyfills for everything out there externally. See `Pointer Events`, `IntersectionObserver`, `fetch`, `Promise`, `Symbol`, `WebAnimation` and maybe more that now align the same behaviour. Being on the global also allows us to completely elide the entire module during the build. 

It looks like we need to update the readme to clarify this, as it currently contradicts the above statement (other than for `Promise` and `Symbol`). We will likely be renaming `shim` to `platform` in 6.0.0 also.

We would definitely love to see a fix for the AMD bug though if that is an issue though.

**Comment by dasa** [comment]
> We would definitely love to see a fix for the AMD bug though if that is an issue.

OK, I can try to create a PR for this. The easy fix would be to enable `esModuleInterop` in the `tsconfig`, but that requires TS 2.7. Would you prefer a check inside the shim itself?

**Comment by matt-gadd** [comment]
@dasa we've been keen to try and support as far back as our initial TS version while we reasonably can. Perhaps switching from:
```ts
import Resize from 'resize-observer-polyfill';
```
to
```ts
import * as Resize from 'resize-observer-polyfill';
```
in the shim will work for now?

**Comment by dasa** [comment]
> The expected behaviour is to be on the global for shim

Does this include array, string, Map, etc?

**Comment by matt-gadd** [comment]
At the moment no, we only aligned the newest external polyfills/ponyfills to be consistent (`Promise` and `Symbol` were the only existing ones that were on the global). 

The array and string implementations are more problematic because they do not have the same api shape due to not being on the primitives prototype. 

We do have plans in general to try and make this more consistent on the road to v6. We could do with being more thorough on stating the end goal for shim/platform in documentation so apologies on the darkness there!

**Comment by dasa** [comment]
> Would you prefer a check inside the shim itself?

PR created
