### ISSUE TITLE
Can meta(Focus) blur ?

### ISSUE THREAD

**Issue by sebilasse** [dojo/framework#338]
**Enhancement**

Package Version: 5

**Code**
``("activeElement" in document) && (<any>document).activeElement.blur();``

Just wondering if this is the way to blur my widget or if this.meta(Focus) can blur the currently focused element without creating an additional element to focus.

I am working on a flexbox select for the material theme https://github.com/dojo/widgets/issues/615 where all the :focus states are already handled by CSS.

**Comment by agubler** [comment]
Hey @sebilasse, sorry this seemed to have got lost in my notifications.

A property called `blur` is available on a vnode, that can be used to blur a dom node, the property accepts a `boolean` to indicate whether to call `blur` or a function that returns a `boolean`.

```ts
render() {
    return v('input', { blur: true });
}

render() {
    return v('input', { blur: () => true });
}
```

It follows the same semantics as `focus` the docs can be found here https://github.com/dojo/framework/blob/master/src/core/README.md#handling-focus.

As for the focus meta, we recommend using the `FocusMixin` combined with the vnode `focus` property instead of using the meta.

Hope that helps!

**Comment by agubler** [comment]
@sebilasse Closing this issue, please re-open if you have any more questions/issues. Thanks!
