### ISSUE TITLE
Render `key` as dom property in `debug` mode

### ISSUE THREAD

**Issue by agubler** [dojo/framework#49]
@tomdye commented on [Mon Jun 11 2018](https://github.com/dojo/widget-core/issues/941)

**Enhancement** 

It would be advantageous to render a widget / DNode `key` onto the corresponding dom node when building for debug. This would be especially helpful when writing integration / BDD tests as the selectors can then target the `key` as we do in our unit tests.

**Comment by tomdye** [comment]
Since raising this issue via Ant we adopted the approach of using `data-test` attributes where we need to target a specific node within functional tests. This solution works well and is recommended in the cypress documentation. The initial suggestion of keeping `key` for a debug mode build would not have allowed us to run functionals against production built code so I believe we can now close this issue.
