### ISSUE TITLE
icache.set does not always invalidate the widget

### ISSUE THREAD

**Issue by rorticus** [dojo/framework#589]
**Bug** 

`icache` middleware does not always invalidate the widget.

Package Version: 

**Code**

https://codesandbox.io/s/dojo-codesandbox-template-n8y99

1. Upon load, note that the `icache.value = Empty`. The icache `value` key is actually `Hello`.
2. Click `Invalidate` to manually invalidate the widget.
3. Notice that the display is correct now.

**Expected behavior:**

When I call `icache.set`, I would expect the widget to invalidate and render again.

**Actual behavior:**

The widget does not invalidate.

**Comment by matt-gadd** [comment]
This is working as designed, no invalidations can occur during the rendering phase itself as this would ultimately lead to numerous infinite render loops due to user error. The value in the example is clearly available in that same render, and simply calling `icache.get` would give you the non stale value.

**Comment by matt-gadd** [comment]
Just to add, we also deliberately give you an api for this scenario in `icache.getOrSet` which allows you to correctly do this in a single call.

**Comment by JamesLMilner** [comment]
Just to chime in here, I think it's worth making this explicit if we can in the documentation as it's a potential footgun. Just taking a look at the middleware docs (https://dojo.io/learn/middleware/available-middleware#icache) I can't see us documenting this behaviour currently (my emphasis):

```
**In all scenarios**, once a value is available and has been stored in the cache, the widget will be marked as invalid so it can be **re-rendered** with the final value available.
```

Just concerned we're not being explicit enough here because it's a pattern a lot of people might try and implement. Maybe we should change this to explain the correct pattern for the case @rorticus depicted?

**Comment by agubler** [comment]
I don’t think it’s really documentation for icache, more over it should be documented that calling invalidate during a render will not schedule a re-render. And I don’t know if that is included in the core widget docs.

**Comment by agubler** [comment]
And people shouldn’t use `get` and then `set` instead of `getOrSet`, that should be made clear.

**Comment by JamesLMilner** [comment]
Yeah that sounds sensible to me. I think your second point probably sits in with the middleware `icache` documentation, but not totally sure where we would put the first point about invalidation during renders. Perhaps somewhere in https://dojo.io/learn/creating-widgets/introduction. Any thoughts on that?
