### ISSUE TITLE
Multiple select does not allow selection of multiple options on creation

### ISSUE THREAD

**Issue by smhigley** [dojo/framework#95]
**Bug**

Creating a native multi-select in vdom does not allow the initial selection of multiple options. This is a minimal recreation: https://codesandbox.io/s/z39779jv7p

It looks like this might be caused by multiple selected `option` nodes being added to the DOM before the parent `select` has had `multiple: true` applied. This would result in the browser interpreting the `selected` attribute as if it were applied to multiple options in a single-select.

**Comment by matt-gadd** [comment]
This is unfortunately due to v3's vdom being based off maquette and it itself having this issue (example: https://codesandbox.io/s/9qm8owj4lr, related issue: https://github.com/AFASSoftware/maquette/issues/139). This is indeed because of the ordering of parent properties and child node applications.

This is fixed in v4 which is an entire rewrite and not based on maquette at all. Because of this though it's unfeasible/unlikely for us to backport a fix into 3.0.
